
redis:
  image: redis
  container_name: cache
  expose:
    - 6379
app:
  build: ./
  volumes:
    - ./:/var/www/app
  links:
    - redis
  ports:
    - ${PORT}:${PORT}
  environment:
    - REDIS_URL=${REDIS_URL}
    - PORT=${PORT}
    - KEY=${KEY}
    - NODE_ENV=${NODE_ENV}
  entrypoint:
    sh -c 'npm i && npm start'